import sys
import os
import tempfile
import subprocess

def run_code_in_sandbox(
    generated_code: str,
    test_assertions: list[str],
    timeout_sec: float = 5.0,
    sandbox_dir: str = None
) -> dict:
    """
    Sandboxed code evaluator corresponding to Section 3.2 of the manuscript.
    
    Evaluates generated Python code against individual unit assertions using isolated
    subprocess calls in temporary script files within a sandbox environment.

    Args:
        generated_code (str): The candidate Python code snippet generated by an LLM.
        test_assertions (list[str]): List of unit assertion expressions (e.g., ["assert add(2, 3) == 5"]).
        timeout_sec (float): Max execution time per assertion in seconds.
        sandbox_dir (str): Path to isolated sandbox directory. Defaults to standard sandbox directory.

    Returns:
        dict: Evaluation results containing per-test binary status S(C_{i,j}, t_{i,k})
              and aggregate Unit Test Pass Rate UR(P_i, Q_j).
    """
    if sandbox_dir is None:
        sandbox_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "sandbox"))
    
    os.makedirs(sandbox_dir, exist_ok=True)
    
    if not test_assertions:
        return {
            "unit_test_pass_rate": 0.0,
            "results": [],
            "total_tests": 0,
            "passed_tests": 0
        }

    results = []
    passed_count = 0
    k_total = len(test_assertions)

    # Quick syntax pre-check on generated_code to fail-fast if candidate code is unparseable
    try:
        compile(generated_code, "<candidate>", "exec")
    except SyntaxError as e:
        syntax_err = f"SyntaxError: {str(e)}"
        results = [
            {
                "test_index": idx + 1,
                "assertion": assertion,
                "status": 0,
                "error": syntax_err
            }
            for idx, assertion in enumerate(test_assertions)
        ]
        return {
            "unit_test_pass_rate": 0.0,
            "results": results,
            "total_tests": k_total,
            "passed_tests": 0
        }

    for idx, assertion in enumerate(test_assertions):
        # Prepare combined script content
        script_content = f"{generated_code}\n\n# Unit Assertion {idx+1}\n{assertion}\n"
        
        # Write to isolated temporary file in sandbox
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".py",
            dir=sandbox_dir,
            delete=False,
            encoding="utf-8"
        ) as tmp_file:
            tmp_path = tmp_file.name
            tmp_file.write(script_content)

        s_status = 0
        error_msg = None

        try:
            completed_proc = subprocess.run(
                [sys.executable, tmp_path],
                capture_output=True,
                text=True,
                timeout=timeout_sec
            )
            
            if completed_proc.returncode == 0:
                s_status = 1
                passed_count += 1
            else:
                stderr_text = completed_proc.stderr.strip()
                error_msg = stderr_text if stderr_text else f"Execution failed with code {completed_proc.returncode}"
        except subprocess.TimeoutExpired:
            error_msg = f"TimeoutExpired: Execution exceeded limit of {timeout_sec} seconds"
        except Exception as e:
            error_msg = f"ExecutionError: {str(e)}"
        finally:
            # Clean up temp execution file
            if os.path.exists(tmp_path):
                try:
                    os.remove(tmp_path)
                except OSError:
                    pass

        results.append({
            "test_index": idx + 1,
            "assertion": assertion,
            "status": s_status,
            "error": error_msg
        })

    unit_test_pass_rate = passed_count / k_total if k_total > 0 else 0.0

    return {
        "unit_test_pass_rate": unit_test_pass_rate,
        "results": results,
        "total_tests": k_total,
        "passed_tests": passed_count
    }
